In [1]:
from pyspark import SparkConf, SparkContext
from operator import add

In [2]:
conf = SparkConf().setMaster("local").setAppName("CustomerOrders")
sc = SparkContext(conf = conf)

In [3]:
input = sc.textFile("file:///home/dmadhok/spark_course/customer-orders.csv")

In [5]:
input.take(10)

['44,8602,37.19',
 '35,5368,65.89',
 '2,3391,40.64',
 '47,6694,14.98',
 '29,680,13.08',
 '91,8900,24.59',
 '70,3959,68.68',
 '85,1733,28.53',
 '53,9900,83.55',
 '14,1505,4.32']

In [12]:
def parseLine(line):
    fields = line.split(',')
    customerID = fields[0]
    dollarAmount = float(fields[2])
    return (customerID, dollarAmount)

In [13]:
customerDollars = input.map(parseLine)
customerDollars.take(5)

[('44', 37.19), ('35', 65.89), ('2', 40.64), ('47', 14.98), ('29', 13.08)]

In [14]:
customerDollars.filter(lambda x: x[0] == '44').take(100)

[('44', 37.19),
 ('44', 99.19),
 ('44', 39.54),
 ('44', 41.88),
 ('44', 66.54),
 ('44', 66.6),
 ('44', 80.96),
 ('44', 93.51),
 ('44', 59.9),
 ('44', 16.47),
 ('44', 10.74),
 ('44', 74.67),
 ('44', 38.25),
 ('44', 29.73),
 ('44', 88.58),
 ('44', 10.13),
 ('44', 86.52),
 ('44', 45.83),
 ('44', 74.23),
 ('44', 0.76),
 ('44', 58.47),
 ('44', 93.8),
 ('44', 73.61),
 ('44', 95.25),
 ('44', 10.55),
 ('44', 93.21),
 ('44', 20.03),
 ('44', 4.04),
 ('44', 37.58),
 ('44', 21.68),
 ('44', 57.47),
 ('44', 63.84),
 ('44', 52.91),
 ('44', 42.26),
 ('44', 75.22),
 ('44', 33.82),
 ('44', 5.93),
 ('44', 56.31),
 ('44', 42.13),
 ('44', 2.71),
 ('44', 84.59),
 ('44', 29.36),
 ('44', 61.0),
 ('44', 85.09),
 ('44', 8.71),
 ('44', 99.88),
 ('44', 15.01),
 ('44', 86.23),
 ('44', 59.6),
 ('44', 15.37),
 ('44', 13.45),
 ('44', 83.93),
 ('44', 7.12),
 ('44', 49.74),
 ('44', 56.1),
 ('44', 99.64),
 ('44', 42.34),
 ('44', 43.35),
 ('44', 95.43),
 ('44', 68.35),
 ('44', 92.06),
 ('44', 77.7),
 ('44', 10.87),
 ('44', 80.3),
 ('44', 21.94),
 ('44', 42.17),
 ('44', 50.24),
 ('44', 42.86),
 ('44', 62.29),
 ('44', 97.08),
 ('44', 14.32),
 ('44', 70.23),
 ('44', 78.18),
 ('44', 9.23),
 ('44', 2.66),
 ('44', 97.39),
 ('44', 21.96),
 ('44', 94.73),
 ('44', 78.13),
 ('44', 42.2),
 ('44', 17.96),
 ('44', 7.0),
 ('44', 30.04),
 ('44', 31.1),
 ('44', 11.57),
 ('44', 15.19),
 ('44', 49.35),
 ('44', 35.41),
 ('44', 93.66),
 ('44', 96.86),
 ('44', 81.09),
 ('44', 94.79)]

In [15]:
customerDollars = customerDollars.reduceByKey(lambda x, y: x + y)

In [16]:
customerDollars.take(5)

[('44', 4756.8899999999985),
 ('35', 5155.419999999999),
 ('2', 5994.59),
 ('47', 4316.299999999999),
 ('29', 5032.529999999999)]

In [18]:
# customerDollars.collect() returns a list from the rdd- running sorted sorts it
sorted(customerDollars.collect())

[('0', 5524.949999999998),
 ('1', 4958.600000000001),
 ('10', 4819.700000000001),
 ('11', 5152.290000000002),
 ('12', 4664.589999999998),
 ('13', 4367.62),
 ('14', 4735.030000000001),
 ('15', 5413.510000000001),
 ('16', 4979.06),
 ('17', 5032.679999999999),
 ('18', 4921.27),
 ('19', 5059.4299999999985),
 ('2', 5994.59),
 ('20', 4836.859999999999),
 ('21', 4707.41),
 ('22', 5019.449999999999),
 ('23', 4042.6499999999987),
 ('24', 5259.920000000003),
 ('25', 5057.610000000001),
 ('26', 5250.4),
 ('27', 4915.889999999999),
 ('28', 5000.709999999998),
 ('29', 5032.529999999999),
 ('3', 4659.63),
 ('30', 4990.72),
 ('31', 4765.05),
 ('32', 5496.050000000004),
 ('33', 5254.659999999998),
 ('34', 5330.8),
 ('35', 5155.419999999999),
 ('36', 4278.049999999997),
 ('37', 4735.200000000002),
 ('38', 4898.460000000002),
 ('39', 6193.109999999999),
 ('4', 4815.050000000002),
 ('40', 5186.429999999999),
 ('41', 5637.62),
 ('42', 5696.840000000003),
 ('43', 5368.83),
 ('44', 4756.8899999999985),
 ('45', 3309.38),
 ('46', 5963.109999999999),
 ('47', 4316.299999999999),
 ('48', 4384.33),
 ('49', 4394.599999999999),
 ('5', 4561.069999999999),
 ('50', 4517.27),
 ('51', 4975.22),
 ('52', 5245.059999999999),
 ('53', 4945.299999999999),
 ('54', 6065.389999999999),
 ('55', 5298.090000000002),
 ('56', 4701.019999999999),
 ('57', 4628.4),
 ('58', 5437.7300000000005),
 ('59', 5642.89),
 ('6', 5397.879999999998),
 ('60', 5040.709999999999),
 ('61', 5497.479999999998),
 ('62', 5253.3200000000015),
 ('63', 5415.150000000001),
 ('64', 5288.689999999996),
 ('65', 5140.3499999999985),
 ('66', 4681.919999999999),
 ('67', 4505.79),
 ('68', 6375.449999999997),
 ('69', 5123.010000000001),
 ('7', 4755.070000000001),
 ('70', 5368.249999999999),
 ('71', 5995.660000000003),
 ('72', 5337.44),
 ('73', 6206.199999999999),
 ('74', 4647.129999999999),
 ('75', 4178.500000000001),
 ('76', 4904.209999999999),
 ('77', 4327.729999999999),
 ('78', 4524.509999999999),
 ('79', 3790.570000000001),
 ('8', 5517.240000000001),
 ('80', 4727.860000000001),
 ('81', 5112.709999999999),
 ('82', 4812.489999999998),
 ('83', 4635.799999999997),
 ('84', 4652.939999999999),
 ('85', 5503.43),
 ('86', 4908.81),
 ('87', 5206.4),
 ('88', 4830.549999999999),
 ('89', 4851.479999999999),
 ('9', 5322.649999999999),
 ('90', 5290.409999999998),
 ('91', 4642.259999999999),
 ('92', 5379.280000000002),
 ('93', 5265.750000000001),
 ('94', 4475.569999999999),
 ('95', 4876.840000000002),
 ('96', 3924.230000000001),
 ('97', 5977.189999999995),
 ('98', 4297.260000000001),
 ('99', 4172.289999999998)]